// Mock data for the DataFlow AI Platform

export const mockDatasets = [
  {
    id: "ds-001",
    name: "Customer Sales Q4 2024",
    source: "Salesforce",
    type: "csv",
    rows: 15420,
    columns: 24,
    quality: 94,
    lastUpdated: "2024-01-15T10:30:00Z",
    status: "active",
    owner: "Sarah Chen",
  },
  {
    id: "ds-002",
    name: "Marketing Campaign Data",
    source: "Mailchimp",
    type: "json",
    rows: 8750,
    columns: 18,
    quality: 87,
    lastUpdated: "2024-01-14T15:45:00Z",
    status: "processing",
    owner: "Mike Johnson",
  },
  {
    id: "ds-003",
    name: "Product Inventory",
    source: "MySQL",
    type: "sql",
    rows: 45000,
    columns: 32,
    quality: 98,
    lastUpdated: "2024-01-15T08:00:00Z",
    status: "active",
    owner: "Emily Davis",
  },
  {
    id: "ds-004",
    name: "User Analytics Events",
    source: "REST API",
    type: "json",
    rows: 125000,
    columns: 45,
    quality: 91,
    lastUpdated: "2024-01-15T11:15:00Z",
    status: "pending_review",
    owner: "Alex Kim",
  },
  {
    id: "ds-005",
    name: "Financial Reports 2024",
    source: "Excel",
    type: "xlsx",
    rows: 3200,
    columns: 28,
    quality: 96,
    lastUpdated: "2024-01-13T09:30:00Z",
    status: "active",
    owner: "David Wilson",
  },
]

export const mockDataContracts = [
  {
    id: "dc-001",
    name: "Sales Data Contract v2.1",
    datasetId: "ds-001",
    version: "2.1.0",
    status: "active",
    fields: 24,
    validationRules: 18,
    lastModified: "2024-01-14T12:00:00Z",
    createdBy: "Sarah Chen",
    approvedBy: "Admin",
  },
  {
    id: "dc-002",
    name: "Marketing Events Schema",
    datasetId: "ds-002",
    version: "1.3.0",
    status: "draft",
    fields: 18,
    validationRules: 12,
    lastModified: "2024-01-15T09:00:00Z",
    createdBy: "Mike Johnson",
    approvedBy: null,
  },
  {
    id: "dc-003",
    name: "Inventory Data Contract",
    datasetId: "ds-003",
    version: "3.0.0",
    status: "active",
    fields: 32,
    validationRules: 25,
    lastModified: "2024-01-12T16:30:00Z",
    createdBy: "Emily Davis",
    approvedBy: "Admin",
  },
]

export const mockSchemaFields = [
  { name: "customer_id", type: "string", required: true, nullable: false, validation: "UUID format" },
  { name: "email", type: "string", required: true, nullable: false, validation: "Email regex" },
  { name: "purchase_date", type: "datetime", required: true, nullable: false, validation: "ISO 8601" },
  { name: "amount", type: "decimal", required: true, nullable: false, validation: "Positive number" },
  { name: "currency", type: "string", required: true, nullable: false, validation: "ISO 4217" },
  { name: "product_id", type: "string", required: true, nullable: false, validation: "SKU format" },
  { name: "quantity", type: "integer", required: true, nullable: false, validation: "Min: 1" },
  { name: "discount", type: "decimal", required: false, nullable: true, validation: "0-100%" },
  { name: "tax", type: "decimal", required: false, nullable: true, validation: "Positive" },
  { name: "shipping_address", type: "object", required: false, nullable: true, validation: "Address schema" },
]

export const mockCleaningTasks = [
  {
    id: "ct-001",
    datasetId: "ds-001",
    type: "duplicate_removal",
    status: "pending_review",
    affectedRows: 234,
    confidence: 96,
    suggestedAction: "Remove 234 duplicate records based on customer_id",
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "ct-002",
    datasetId: "ds-001",
    type: "date_normalization",
    status: "pending_review",
    affectedRows: 1250,
    confidence: 99,
    suggestedAction: "Convert all dates to ISO 8601 format",
    createdAt: "2024-01-15T10:05:00Z",
  },
  {
    id: "ct-003",
    datasetId: "ds-002",
    type: "currency_normalization",
    status: "approved",
    affectedRows: 3420,
    confidence: 94,
    suggestedAction: "Normalize currencies to USD",
    createdAt: "2024-01-14T14:30:00Z",
  },
  {
    id: "ct-004",
    datasetId: "ds-001",
    type: "missing_value_detection",
    status: "pending_review",
    affectedRows: 89,
    confidence: 88,
    suggestedAction: "Fill missing values with median for numerical columns",
    createdAt: "2024-01-15T10:10:00Z",
  },
  {
    id: "ct-005",
    datasetId: "ds-004",
    type: "anomaly_detection",
    status: "rejected",
    affectedRows: 12,
    confidence: 72,
    suggestedAction: "Flag 12 records with unusual patterns",
    createdAt: "2024-01-14T16:00:00Z",
  },
]

export const mockTeamMembers = [
  { id: "u-001", name: "Sarah Chen", role: "Admin", avatar: "SC", email: "sarah@company.com", status: "online" },
  { id: "u-002", name: "Mike Johnson", role: "Data Engineer", avatar: "MJ", email: "mike@company.com", status: "online" },
  { id: "u-003", name: "Emily Davis", role: "Data Analyst", avatar: "ED", email: "emily@company.com", status: "away" },
  { id: "u-004", name: "Alex Kim", role: "Business User", avatar: "AK", email: "alex@company.com", status: "offline" },
  { id: "u-005", name: "David Wilson", role: "Reviewer", avatar: "DW", email: "david@company.com", status: "online" },
]

export const mockActivities = [
  {
    id: "a-001",
    user: "Sarah Chen",
    action: "approved",
    target: "Sales Data Contract v2.1",
    timestamp: "2024-01-15T11:30:00Z",
    type: "contract",
  },
  {
    id: "a-002",
    user: "Mike Johnson",
    action: "uploaded",
    target: "Marketing Campaign Data",
    timestamp: "2024-01-15T10:45:00Z",
    type: "dataset",
  },
  {
    id: "a-003",
    user: "Emily Davis",
    action: "commented on",
    target: "Q4 Revenue Dashboard",
    timestamp: "2024-01-15T09:20:00Z",
    type: "dashboard",
  },
  {
    id: "a-004",
    user: "Alex Kim",
    action: "requested review for",
    target: "User Analytics Events",
    timestamp: "2024-01-15T08:15:00Z",
    type: "dataset",
  },
  {
    id: "a-005",
    user: "David Wilson",
    action: "rejected",
    target: "Anomaly Detection Task",
    timestamp: "2024-01-14T17:00:00Z",
    type: "cleaning",
  },
]

export const mockNotifications = [
  {
    id: "n-001",
    title: "Review Requested",
    message: "Alex Kim requested your review on User Analytics Events",
    read: false,
    timestamp: "2024-01-15T08:15:00Z",
  },
  {
    id: "n-002",
    title: "Contract Approved",
    message: "Sales Data Contract v2.1 has been approved",
    read: false,
    timestamp: "2024-01-15T11:30:00Z",
  },
  {
    id: "n-003",
    title: "AI Suggestions Ready",
    message: "3 new data cleaning suggestions for Customer Sales Q4 2024",
    read: true,
    timestamp: "2024-01-15T10:10:00Z",
  },
  {
    id: "n-004",
    title: "Pipeline Completed",
    message: "Marketing data pipeline completed successfully",
    read: true,
    timestamp: "2024-01-14T15:45:00Z",
  },
]

export const mockChartData = {
  dataQuality: [
    { month: "Aug", score: 82 },
    { month: "Sep", score: 85 },
    { month: "Oct", score: 88 },
    { month: "Nov", score: 91 },
    { month: "Dec", score: 89 },
    { month: "Jan", score: 94 },
  ],
  pipelineActivity: [
    { day: "Mon", runs: 45, failures: 2 },
    { day: "Tue", runs: 52, failures: 1 },
    { day: "Wed", runs: 48, failures: 3 },
    { day: "Thu", runs: 61, failures: 0 },
    { day: "Fri", runs: 55, failures: 2 },
    { day: "Sat", runs: 23, failures: 0 },
    { day: "Sun", runs: 18, failures: 1 },
  ],
  dataSourceDistribution: [
    { name: "Salesforce", value: 35, color: "var(--chart-1)" },
    { name: "MySQL", value: 28, color: "var(--chart-2)" },
    { name: "REST APIs", value: 20, color: "var(--chart-3)" },
    { name: "Excel/CSV", value: 12, color: "var(--chart-4)" },
    { name: "Others", value: 5, color: "var(--chart-5)" },
  ],
  monthlyIngestion: [
    { month: "Aug", records: 1200000 },
    { month: "Sep", records: 1450000 },
    { month: "Oct", records: 1680000 },
    { month: "Nov", records: 1520000 },
    { month: "Dec", records: 1890000 },
    { month: "Jan", records: 2100000 },
  ],
}

export const mockChatMessages = [
  {
    id: "m-001",
    role: "assistant" as const,
    content: "Hello! I'm your AI data assistant. I can help you explore datasets, generate insights, clean data, and create visualizations. What would you like to do today?",
    timestamp: "2024-01-15T10:00:00Z",
  },
]

export const mockSuggestedPrompts = [
  "Show duplicate records in Sales Data",
  "Normalize all currencies to USD",
  "Generate sales dashboard for Q4",
  "Show missing values analysis",
  "Create revenue trend visualization",
  "Explain the customer segmentation",
]

export const mockLineageNodes = [
  { id: "source-1", type: "source", label: "Salesforce CRM", x: 50, y: 100 },
  { id: "source-2", type: "source", label: "MySQL Database", x: 50, y: 200 },
  { id: "source-3", type: "source", label: "REST API", x: 50, y: 300 },
  { id: "ingest-1", type: "process", label: "Data Ingestion", x: 200, y: 200 },
  { id: "clean-1", type: "process", label: "AI Preprocessing", x: 350, y: 200 },
  { id: "validate-1", type: "process", label: "Validation", x: 500, y: 200 },
  { id: "approve-1", type: "approval", label: "Human Approval", x: 650, y: 200 },
  { id: "store-1", type: "storage", label: "Data Warehouse", x: 800, y: 200 },
  { id: "insight-1", type: "ai", label: "AI Insights", x: 950, y: 150 },
  { id: "dashboard-1", type: "output", label: "Dashboards", x: 1100, y: 100 },
  { id: "collab-1", type: "output", label: "Collaboration", x: 1100, y: 200 },
  { id: "reports-1", type: "output", label: "Reports", x: 1100, y: 300 },
]

export const mockLineageEdges = [
  { from: "source-1", to: "ingest-1" },
  { from: "source-2", to: "ingest-1" },
  { from: "source-3", to: "ingest-1" },
  { from: "ingest-1", to: "clean-1" },
  { from: "clean-1", to: "validate-1" },
  { from: "validate-1", to: "approve-1" },
  { from: "approve-1", to: "store-1" },
  { from: "store-1", to: "insight-1" },
  { from: "insight-1", to: "dashboard-1" },
  { from: "insight-1", to: "collab-1" },
  { from: "insight-1", to: "reports-1" },
]
